/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package apppenjualan.form;

import apppenjualan.AppPenjualan;
import apppenjualan.control.BarangController;
import apppenjualan.control.FakturController;
import apppenjualan.control.KwitansiController;
import apppenjualan.control.PelangganController;
import apppenjualan.data.*;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gxry
 */
public class Frmkwitansi extends javax.swing.JInternalFrame implements NavigatorFormInt {

    DateFormat dfddmmyyyy = new SimpleDateFormat("dd/MM/yyyy"); 
    //model tanggal co: 01/01/2013 
     
    DecimalFormat dftitik = new DecimalFormat("#,###"); 
    DefaultTableModel tmodelfaktur; //operasional tabel 
    Object[] obj; //baris tabel 
    
    Faktur f = new Faktur();  
    FakturController fctrl = new  
    FakturController(AppPenjualan.emf); 
    
    Kwitansi k = new Kwitansi(); 
    KwitansiController kctrl = new  
    KwitansiController(AppPenjualan.emf); 
    
    Pelanggan plg = new Pelanggan(); 
    PelangganController plgctrl = new  
    PelangganController(AppPenjualan.emf); 
    
    BarangController bctrl = new  
    BarangController(AppPenjualan.emf);
    
    /**
     * Creates new form FrmBarang
     */
    public Frmkwitansi() {
        initComponents(); 
        jfmtTanggalKwitansi.setText( 
        dfddmmyyyy.format(new Date())); 
        tmodelfaktur = (DefaultTableModel)  
        jtblFaktur.getModel(); 
        obj = new Object[jtblFaktur.getRowCount()]; 
         
        clearTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtNamaPelanggan = new javax.swing.JTextField();
        jtxtNomorFaktur = new javax.swing.JTextField();
        jtxtKodePelanggan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jfmtTanggalFaktur = new javax.swing.JFormattedTextField();
        jtxtGrandTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblFaktur = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jtxtNomorKwitansi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jfmtTanggalKwitansi = new javax.swing.JFormattedTextField();

        setTitle("Kwitansi");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Kwitansi");

        jLabel2.setText("Nomor Faktur:");

        jLabel3.setText("Kode Pelanggan:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Grand Total:");

        jtxtNamaPelanggan.setEditable(false);

        jtxtNomorFaktur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtNomorFakturKeyPressed(evt);
            }
        });

        jtxtKodePelanggan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtKodePelangganKeyPressed(evt);
            }
        });

        jLabel5.setText("Tanggal Faktur:");

        jfmtTanggalFaktur.setEditable(false);
        jfmtTanggalFaktur.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        jtxtGrandTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtGrandTotalKeyPressed(evt);
            }
        });

        jtblFaktur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Kode Barang", "Nama Barang", "Harga", "Qty", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblFaktur.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtblFakturPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jtblFaktur);

        jLabel6.setText("Nomor Kwitansi:");

        jtxtNomorKwitansi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtNomorKwitansiKeyPressed(evt);
            }
        });

        jLabel7.setText("Tanggal Kwitansi:");

        jfmtTanggalKwitansi.setEditable(false);
        jfmtTanggalKwitansi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(30, 30, 30)
                                .addComponent(jtxtKodePelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtNomorKwitansi, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtNomorFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jfmtTanggalKwitansi, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jfmtTanggalFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jtxtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jtxtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jfmtTanggalKwitansi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtNomorKwitansi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jfmtTanggalFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jtxtNomorFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtKodePelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNomorFakturKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNomorFakturKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { 
            jtxtNomorKwitansi.setText(""); 
            jfmtTanggalKwitansi.setText(dfddmmyyyy.format(new Date())); 
            checkDataFaktur(); 
            //k = fctrl. (jtxtKodePelanggan.getText());
            
        }
    }//GEN-LAST:event_jtxtNomorFakturKeyPressed

    private void jtxtGrandTotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtGrandTotalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtGrandTotalKeyPressed

    private void jtxtKodePelangganKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtKodePelangganKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { 
            plg = plgctrl.findPelanggan(jtxtKodePelanggan.getText()); 
            if (plg == null) { 
                JOptionPane.showMessageDialog(null, jtxtKodePelanggan.getText() +  " Tidak Diketemukan "); 
                jtxtKodePelanggan.setText(""); 
                jtxtNamaPelanggan.setText(""); 
                jtxtKodePelanggan.requestFocus();  
                //cursor kembali ke kode 
            } else { 
                jtxtKodePelanggan.setText(plg.getKodepelanggan()); 
                jtxtNamaPelanggan.setText(plg.getNamapelanggan()); 
                jtblFaktur.requestFocus(); 
            } 
        }
    }//GEN-LAST:event_jtxtKodePelangganKeyPressed

    private void jtblFakturPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtblFakturPropertyChange
        // TODO add your handling code here:
        //ambil baris dan kolom yang terseleksi 
        int row = jtblFaktur.getSelectedRow(); 
        int col = jtblFaktur.getSelectedColumn(); 
         
        if ( row > -1) { 
            //jika ada yang terseleksi 
            if (col == 1) { 
                //jika kode barang (col 1) berubah 
                Barang brg = bctrl.findBarang(tmodelfaktur.getValueAt(row, col)+""); 
                if (brg != null ) { 
                    //jika kode barang (col 1) ketemu 
                    tmodelfaktur.setValueAt(brg.getKodebarang(), row, col); 
                    tmodelfaktur.setValueAt(brg.getNamabarang(), row, col + 1); 
                    tmodelfaktur.setValueAt(brg.getHargaStandard(), row, col + 2); 
                    jtblFaktur.changeSelection(row, col+3, false, false); 
                } else { 
                    //jika kode barang (col 1) tidak ketemu 
                    tmodelfaktur.setValueAt("", row, col + 1); 
                    tmodelfaktur.setValueAt(0, row, col + 2); 
                } 
            } 
            if (tmodelfaktur.getValueAt(tmodelfaktur.getRowCount()-1, 1)!= null){ 
                //jika nomor faktur tidak kosong  
                //dan baris terakhir tidak kosong maka tambah baris 
                tmodelfaktur.addRow(obj); 
            }             
            if (col == 4) { 
                jtblFaktur.changeSelection(tmodelfaktur.getRowCount()-1, 1, false, false); 
            } 
            hitungTotal();
        }
    }//GEN-LAST:event_jtblFakturPropertyChange

    private void jtxtNomorKwitansiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNomorKwitansiKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { 
            findData();  
        }
    }//GEN-LAST:event_jtxtNomorKwitansiKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JFormattedTextField jfmtTanggalFaktur;
    private javax.swing.JFormattedTextField jfmtTanggalKwitansi;
    private javax.swing.JTable jtblFaktur;
    private javax.swing.JTextField jtxtGrandTotal;
    private javax.swing.JTextField jtxtKodePelanggan;
    private javax.swing.JTextField jtxtNamaPelanggan;
    private javax.swing.JTextField jtxtNomorFaktur;
    private javax.swing.JTextField jtxtNomorKwitansi;
    // End of variables declaration//GEN-END:variables

    @Override
    public void clearData() {
        //throw new UnsupportedOperationException("Not supported yet.");
        jtxtNomorFaktur.setText(""); 
        jfmtTanggalFaktur.setText(""); 
        jtxtKodePelanggan.setText(""); 
        jtxtNamaPelanggan.setText(""); 
        clearTable();
    }

    @Override
    public void newData() {
        //throw new UnsupportedOperationException("Not supported yet.");
        jtxtNomorKwitansi.setText(""); 
        jfmtTanggalKwitansi.setText(dfddmmyyyy.format(new Date())); 
        clearData();
    }

    @Override
    public void saveData() {
        //throw new UnsupportedOperationException("Not supported yet.");
        Faktur ffind = fctrl.findFaktur(jtxtNomorFaktur.getText()); 
        if (ffind == null){ 
            JOptionPane.showMessageDialog(null, "Faktur Tidak Boleh Kosong");
        } else { 
            f = ffind; 
            Kwitansi kfind = kctrl.findKwitansi(jtxtNomorKwitansi.getText()); 
            if (kfind == null) { 
                k = new Kwitansi(); 
                k.setNomorKwitansi(kctrl.createNomorKwitansi());
            } else { 
                k = kfind; 
            } 
            setData(); 
            if (kfind == null) { 
                try { 
                    kctrl.create(k); 
                    jtxtNomorKwitansi.setText(k.getNomorKwitansi()); 
                    JOptionPane.showMessageDialog(null, "Penyimpanan Kwitansi Berhasil"); 
                } catch (Exception ex) { 
                    JOptionPane.showMessageDialog(null, "Penyimpanan Kwitansi Gagal : " + ex.getMessage()); 
                } 
            } else { 
                try { 
                    kctrl.edit(k); 
                    JOptionPane.showMessageDialog(null, "Penyimpanan Kwitansi Berhasil" ); 
                } catch (Exception ex) { 
                    ex.printStackTrace(); 
                    JOptionPane.showMessageDialog(null, "Penyimpanan Kwitansi Gagal : " + ex.getMessage()); 
                } 
            } 
        } 
    }

    @Override
    public void setData() {
        //throw new UnsupportedOperationException("Not supported yet.");
        try { 
            k.setTanggalKwitansi(dfddmmyyyy.parse(jfmtTanggalKwitansi.getText())); 
        } catch (ParseException ex) {} 
        k.setNomorFaktur(f);
    }

    @Override
    public void delete() {
        //throw new UnsupportedOperationException("Not supported yet.");
        try { 
            kctrl.destroy(jtxtNomorKwitansi.getText()); 
            JOptionPane.showMessageDialog(null, "Penghapusan Selesai"); 
        } catch (Exception ex) { 
            JOptionPane.showMessageDialog(null, "Penghapusan tidak bisa karena " + ex.getMessage()); 
        } 
        newData();
    }

    @Override
    public void findData() {
        //throw new UnsupportedOperationException("Not supported yet.");
        clearData(); 
         
        Kwitansi kfind = kctrl.findKwitansi(jtxtNomorKwitansi.getText()); 
        if (kfind == null) { 
            newData(); 
        } else { 
            k = kfind; 
            showData(); 
        }
    }

    @Override
    public void showData() {
        //throw new UnsupportedOperationException("Not supported yet.");
        if (k == null) { 
            newData(); 
        } else { 
            jtxtNomorKwitansi.setText(k.getNomorKwitansi()); 
            jfmtTanggalKwitansi.setText(dfddmmyyyy.format(k.getTanggalKwitansi())); 
            jtxtNomorFaktur.setText(k.getNomorFaktur().getNomorFaktur()); 
             
            findDataFaktur(); 
        }
    }

    private void clearTable() { 
        int row = tmodelfaktur.getRowCount();       
        while(row > 0){   
           row--;         
           tmodelfaktur.removeRow(row); 
        }     
    }
    
    private void checkDataFaktur() {
        Faktur ffind = fctrl.findFaktur(jtxtNomorFaktur.getText()); 
        //JOptionPane.showMessageDialog(null, ffind);
        boolean cekfaktur = kctrl.checkNomorFaktur(ffind); 
        if (!cekfaktur) { 
            f = ffind; 
            showDataFaktur(); 
        } else { 
            JOptionPane.showMessageDialog(null, "Nomor Faktur : " + jtxtNomorFaktur.getText() + " Sudah Pernah Diproses"); 
            clearData(); 
        }
    }
    
    private void findDataFaktur() { 
        f = fctrl.findFaktur(jtxtNomorFaktur.getText()); 
        showDataFaktur(); 
    }
    
    private void showDataFaktur() { 
        clearData(); 
        if (f != null) { 
            jtxtNomorFaktur.setText(f.getNomorFaktur()); 
            jfmtTanggalFaktur.setText(dfddmmyyyy.format(f.getTanggalFaktur()));
            if (f.getKodePelanggan() != null) { 
                jtxtKodePelanggan.setText(f.getKodePelanggan().getKodepelanggan()); 
                jtxtNamaPelanggan.setText(f.getKodePelanggan().getNamapelanggan()); 
            }         
            for (Fakturdetail fd : f.getFakturdetailCollection()) { 
                tmodelfaktur.addRow(obj); 
                tmodelfaktur.setValueAt(fd.getId(), tmodelfaktur.getRowCount() - 1, 0); 
                tmodelfaktur.setValueAt(fd.getKodeBarang().getKodebarang(), tmodelfaktur.getRowCount() - 1, 1); 
                tmodelfaktur.setValueAt(fd.getKodeBarang().getNamabarang(), tmodelfaktur.getRowCount() - 1, 2); 
                tmodelfaktur.setValueAt(fd.getHarga(), tmodelfaktur.getRowCount() - 1, 3); 
                tmodelfaktur.setValueAt(fd.getQty(), tmodelfaktur.getRowCount() - 1, 4); 
            } 
        hitungTotal(); 
        } 
    }
    
    private void setDataDetail(Fakturdetail fdetail, int i){ 
        Barang b = bctrl.findBarang(tmodelfaktur.getValueAt(i, 1)+""); 
        fdetail.setKodeBarang(b); 
        double harga = 0; 
        try { 
            harga = Double.parseDouble(tmodelfaktur.getValueAt(i, 3)+""); 
        } catch (Exception e) {} 
        fdetail.setHarga(harga); 
        
        int qty = 0; 
        try { 
            qty = Integer.parseInt(tmodelfaktur.getValueAt(i, 4)+""); 
        } catch(Exception e) {} 
        fdetail.setQty(qty);                 
    }
    
    private void hitungTotal(){ 
        double grandtotal = 0; 
        try { 
            for (int i = 0; i < tmodelfaktur.getRowCount(); i++) { 
                double total  = 0; 
                total =  Double.parseDouble(tmodelfaktur.getValueAt(i, 3)+ "") * Double.parseDouble(tmodelfaktur.getValueAt(i, 4)+""); 
                tmodelfaktur.setValueAt(total, i, 5); 
                grandtotal += total; 
            } 
        } catch(Exception e) {} 
 
        jtxtGrandTotal.setText(dftitik.format(grandtotal));
    }
    
    @Override
    public void printData() {
        //throw new UnsupportedOperationException("Not supported yet.");
        
    }

    @Override
    public void moveFirst() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void movePrevious() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void moveNext() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void moveLast() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
