/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package apppenjualan.form;

import java.awt.Color;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import java.util.ArrayList;

/**
 *
 * @author gxry
 */
public class FrmMain extends javax.swing.JFrame {

    Login frmlogin;
    FrmBarang frmbarang;
    FrmPelanggan frmpelanggan;
    FrmPenjualan frmpenjualan;
    Frmkwitansi frmkwitansi;
    ArrayList<String> data = new ArrayList();
    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        
        /*
        UIManager.put("nimbusBase", new Color(244));
        UIManager.put("nimbusBlueGrey", new Color(255));
        UIManager.put("control", new Color(123));
        */
        
        try {
            for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
    // If Nimbus is not available, you can set the GUI to another look and feel.
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jbtnNew = new javax.swing.JButton();
        jbtnSave = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jbtnFirst = new javax.swing.JButton();
        jbtnPrev = new javax.swing.JButton();
        jbtnNext = new javax.swing.JButton();
        jbtnLast = new javax.swing.JButton();
        jbtnClose = new javax.swing.JButton();
        jdesktoppane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtUser = new javax.swing.JTextField();
        jbtnLogin = new javax.swing.JButton();
        jtxtPassword = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmnuMaster = new javax.swing.JMenu();
        jmniBarang = new javax.swing.JMenuItem();
        jmniPelanggan = new javax.swing.JMenuItem();
        jmnuTransaksi = new javax.swing.JMenu();
        jmniPenjualan = new javax.swing.JMenuItem();
        jmniKwiTansi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);

        jbtnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_newfile.gif"))); // NOI18N
        jbtnNew.setText("New");
        jbtnNew.setFocusable(false);
        jbtnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnNew.setName("");
        jbtnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNewActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtnNew);

        jbtnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_save.gif"))); // NOI18N
        jbtnSave.setText("Save");
        jbtnSave.setFocusable(false);
        jbtnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtnSave);

        jbtnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_del.gif"))); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.setFocusable(false);
        jbtnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtnDelete);

        jbtnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print.gif"))); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.setFocusable(false);
        jbtnPrint.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnPrint.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtnPrint);

        jbtnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_move_first.gif"))); // NOI18N
        jbtnFirst.setText("First");
        jbtnFirst.setFocusable(false);
        jbtnFirst.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnFirst.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFirstActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtnFirst);

        jbtnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_move_prev.gif"))); // NOI18N
        jbtnPrev.setText("Prev");
        jbtnPrev.setFocusable(false);
        jbtnPrev.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnPrev.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrevActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtnPrev);

        jbtnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_move_next.gif"))); // NOI18N
        jbtnNext.setText("Next");
        jbtnNext.setFocusable(false);
        jbtnNext.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnNext.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNextActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtnNext);

        jbtnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_move_last.gif"))); // NOI18N
        jbtnLast.setText("Last");
        jbtnLast.setFocusable(false);
        jbtnLast.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnLast.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLastActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtnLast);

        jbtnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_close.gif"))); // NOI18N
        jbtnClose.setText("Close");
        jbtnClose.setFocusable(false);
        jbtnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCloseActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtnClose);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jLabel1.setBounds(10, 10, 620, 90);
        jdesktoppane.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator1.setBounds(0, 72, 640, 0);
        jdesktoppane.add(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Password:");
        jLabel2.setBounds(230, 160, 70, 14);
        jdesktoppane.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Username:");
        jLabel3.setBounds(230, 130, 70, 15);
        jdesktoppane.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jtxtUser.setBackground(new java.awt.Color(204, 204, 204));
        jtxtUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtxtUser.setBorder(null);
        jtxtUser.setBounds(310, 130, 100, 20);
        jdesktoppane.add(jtxtUser, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jbtnLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnLogin.setText("Login");
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });
        jbtnLogin.setBounds(270, 200, 69, 25);
        jdesktoppane.add(jbtnLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jtxtPassword.setBackground(new java.awt.Color(204, 204, 204));
        jtxtPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtxtPassword.setBorder(null);
        jtxtPassword.setBounds(310, 160, 100, 20);
        jdesktoppane.add(jtxtPassword, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jmnuMaster.setText("Master");
        jmnuMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuMasterActionPerformed(evt);
            }
        });

        jmniBarang.setText("Barang");
        jmniBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmniBarangActionPerformed(evt);
            }
        });
        jmnuMaster.add(jmniBarang);

        jmniPelanggan.setText("Pelanggan");
        jmniPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmniPelangganActionPerformed(evt);
            }
        });
        jmnuMaster.add(jmniPelanggan);

        jMenuBar1.add(jmnuMaster);

        jmnuTransaksi.setText("Transaksi");

        jmniPenjualan.setText("Penjualan");
        jmniPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmniPenjualanActionPerformed(evt);
            }
        });
        jmnuTransaksi.add(jmniPenjualan);

        jmniKwiTansi.setText("Kwitansi");
        jmniKwiTansi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmniKwiTansiActionPerformed(evt);
            }
        });
        jmnuTransaksi.add(jmniKwiTansi);

        jMenuBar1.add(jmnuTransaksi);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
            .addComponent(jdesktoppane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdesktoppane, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private static java.util.List<java.lang.String> login(java.lang.String user, java.lang.String password) {
        pakeg.ServiceNetproService service = new pakeg.ServiceNetproService();
        pakeg.ServiceNetpro port = service.getServiceNetproPort();
        return port.login(user, password);
    }
    
    private void jmniBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmniBarangActionPerformed
        // TODO add your handling code here:
        if (frmbarang == null) { 
            frmbarang = new FrmBarang(); 
        } 
        jdesktoppane.setVisible(true);
        showForm(frmbarang);
        Aktif();
    }//GEN-LAST:event_jmniBarangActionPerformed

    public void Aktif()
    {
        jbtnNew.setEnabled(true);
        jbtnSave.setEnabled(true);
        jbtnDelete.setEnabled(true);
        jbtnPrint.setEnabled(true);
        jbtnFirst.setEnabled(true);
        jbtnPrev.setEnabled(true);
        jbtnNext.setEnabled(true);
        jbtnLast.setEnabled(true);
        jbtnClose.setEnabled(true);
    }
    
    public void NonAktif()
    {
        jbtnNew.setEnabled(false);
        jbtnSave.setEnabled(false);
        jbtnDelete.setEnabled(false);
        jbtnPrint.setEnabled(false);
        jbtnFirst.setEnabled(false);
        jbtnPrev.setEnabled(false);
        jbtnNext.setEnabled(false);
        jbtnLast.setEnabled(false);
        jbtnClose.setEnabled(false);
    }
    
    private void jmniPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmniPelangganActionPerformed
        // TODO add your handling code here:
        if (frmpelanggan == null) { 
            frmpelanggan = new FrmPelanggan(); 
        } 
        jdesktoppane.setVisible(true);
        showForm(frmpelanggan);
        Aktif();
    }//GEN-LAST:event_jmniPelangganActionPerformed

    private void jbtnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNewActionPerformed
        // TODO add your handling code here:
        navformint = (NavigatorFormInt)  
        jdesktoppane.getSelectedFrame(); 
        navformint.newData();
    }//GEN-LAST:event_jbtnNewActionPerformed

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed
        // TODO add your handling code here:
        navformint = (NavigatorFormInt)  
        jdesktoppane.getSelectedFrame(); 
        navformint.saveData();                
        JOptionPane.showMessageDialog(null, "Simpan Selesai");
    }//GEN-LAST:event_jbtnSaveActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        // TODO add your handling code here:
        int jawaban =  JOptionPane.showConfirmDialog (null, "Delete This Data ?", "Delete ? ", JOptionPane.YES_NO_OPTION); 
        if (jawaban == JOptionPane.YES_OPTION ) { 
            navformint = (NavigatorFormInt)  
            jdesktoppane.getSelectedFrame(); 
            navformint.delete(); 
        }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        // TODO add your handling code here:
        navformint = (NavigatorFormInt)  
        jdesktoppane.getSelectedFrame(); 
        navformint.printData();
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jmnuMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuMasterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmnuMasterActionPerformed

    private void jmniPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmniPenjualanActionPerformed
        // TODO add your handling code here:
        if (frmpenjualan == null) { 
            frmpenjualan = new FrmPenjualan(); 
        } 
        jdesktoppane.setVisible(true);
        showForm(frmpenjualan);
        Aktif();
    }//GEN-LAST:event_jmniPenjualanActionPerformed

    private void jmniKwiTansiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmniKwiTansiActionPerformed
        // TODO add your handling code here:
        if (frmkwitansi == null) { 
            frmkwitansi = new Frmkwitansi(); 
        } 
        jdesktoppane.setVisible(true);
        showForm(frmkwitansi);
        Aktif();
    }//GEN-LAST:event_jmniKwiTansiActionPerformed

    private void jbtnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFirstActionPerformed
        // TODO add your handling code here:
        try {
            navformint = (NavigatorFormInt) jdesktoppane.getSelectedFrame();
            navformint.moveFirst();
            } catch(Exception exp) {}
    }//GEN-LAST:event_jbtnFirstActionPerformed

    private void jbtnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrevActionPerformed
        // TODO add your handling code here:
        try {
            navformint = (NavigatorFormInt) jdesktoppane.getSelectedFrame();
            navformint.movePrevious();
        } catch(Exception exp) {}
    }//GEN-LAST:event_jbtnPrevActionPerformed

    private void jbtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNextActionPerformed
        // TODO add your handling code here:
        try {
            navformint = (NavigatorFormInt) jdesktoppane.getSelectedFrame();
            navformint.moveNext();
        } catch(Exception exp) {}
    }//GEN-LAST:event_jbtnNextActionPerformed

    private void jbtnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLastActionPerformed
        // TODO add your handling code here:
        try {
            navformint = (NavigatorFormInt) jdesktoppane.getSelectedFrame();
            navformint.moveLast();
        } catch(Exception exp) {}
    }//GEN-LAST:event_jbtnLastActionPerformed

    private void jbtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCloseActionPerformed
        // TODO add your handling code here:
        jdesktoppane.setVisible(false);
        NonAktif();
    }//GEN-LAST:event_jbtnCloseActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
        /*
        if (frmlogin == null) { 
            frmlogin = new Login(); 
        } 
        jdesktoppane.setVisible(true);
        showForm(frmlogin);
        jmnuMaster.setEnabled(false);
        jmnuTransaksi.setEnabled(false);
        * 
        */
    }//GEN-LAST:event_formWindowActivated

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        // TODO add your handling code here:
        String user = jtxtUser.getText();
        String password = jtxtPassword.getText();
        data = (ArrayList<String>) login(user, password);

        if (data.get(0)!=null && data.get(1)!=null)
        {
            JOptionPane.showMessageDialog(null, "Selamat Datang di Program Penjualan");
            jmnuMaster.setEnabled(true);
            jmnuTransaksi.setEnabled(true);
            //jdesktoppane.setVisible(false);
            jtxtUser.setVisible(false);
            jtxtPassword.setVisible(false);
            jbtnLogin.setVisible(false);
            jLabel1.setVisible(false);
            jLabel2.setVisible(false);
            jLabel3.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Username dan Password Anda salah!");
        }
    }//GEN-LAST:event_jbtnLoginActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        NonAktif();
        jmnuMaster.setEnabled(false);
        jmnuTransaksi.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbtnClose;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnFirst;
    private javax.swing.JButton jbtnLast;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnNew;
    private javax.swing.JButton jbtnNext;
    private javax.swing.JButton jbtnPrev;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JDesktopPane jdesktoppane;
    private javax.swing.JMenuItem jmniBarang;
    private javax.swing.JMenuItem jmniKwiTansi;
    private javax.swing.JMenuItem jmniPelanggan;
    private javax.swing.JMenuItem jmniPenjualan;
    private javax.swing.JMenu jmnuMaster;
    private javax.swing.JMenu jmnuTransaksi;
    private javax.swing.JPasswordField jtxtPassword;
    private javax.swing.JTextField jtxtUser;
    // End of variables declaration//GEN-END:variables

    NavigatorFormInt navformint ; 
  
    private void showForm(Object obj) { 
        JInternalFrame jf = null; 
        //jika objek merupakan JInternalFrame 
        if (obj instanceof JInternalFrame) { 
            jf = (JInternalFrame) obj; 
            //Apabila belum pernah ditampilkan maka ditambahkan pada 
            //jdesktoppane 
            if (!jf.isVisible()) { 
                jdesktoppane.add(jf); 
            } 
            //tampilkan objek JinternalFrame 
            jf.setVisible(true); 
            try {         
                jf.setMaximum(true); 
                jf.setSelected(true);     
            } catch (java.beans.PropertyVetoException e) { 
                e.printStackTrace(); 
            }         
        }         
    }
}
