/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package apppenjualan.form;

import apppenjualan.AppPenjualan;
import apppenjualan.browse.FrmBrowseBarang;
import apppenjualan.browse.FrmBrowsePelanggan;
import apppenjualan.control.BarangController;
import apppenjualan.control.FakturController;
import apppenjualan.control.PelangganController;
import apppenjualan.data.Barang;
import apppenjualan.data.Faktur;
import apppenjualan.data.Fakturdetail;
import apppenjualan.data.Pelanggan;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.HashMap;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author gxry
 */
public class FrmPenjualan extends javax.swing.JInternalFrame implements NavigatorFormInt {

    DateFormat dfddmmyyyy = new SimpleDateFormat("dd/MM/yyyy");  
     
    DecimalFormat dftitik = new DecimalFormat("#,###"); 
    DefaultTableModel tmodelfaktur; //operasional tabel 
    Object[] obj; //baris tabel 
     
    Faktur f = new Faktur();  
    FakturController fctrl = new FakturController(AppPenjualan.emf); 
     
    Pelanggan plg = new Pelanggan(); 
    PelangganController plgctrl = new 
    PelangganController(AppPenjualan.emf); 
 
    BarangController bctrl = new BarangController(AppPenjualan.emf);
    
    /**
     * Creates new form FrmBarang
     */
    public FrmPenjualan() {
        initComponents();
        jfmtTanggalFaktur.setText(dfddmmyyyy.format(new Date())); 
        tmodelfaktur = (DefaultTableModel) jtblFaktur.getModel(); 
        obj = new Object[jtblFaktur.getRowCount()]; 
        clearTable(); 
        tmodelfaktur.addRow(obj);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtNamaPelanggan = new javax.swing.JTextField();
        jtxtNomorFaktur = new javax.swing.JTextField();
        jtxtKodePelanggan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jfmtTanggalFaktur = new javax.swing.JFormattedTextField();
        jtxtGrandTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblFaktur = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setTitle("Penjualan");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Penjualan");

        jLabel2.setText("Nomor Faktur:");

        jLabel3.setText("Kode Pelanggan:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Grand Total:");

        jtxtNamaPelanggan.setEditable(false);

        jtxtNomorFaktur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtNomorFakturKeyPressed(evt);
            }
        });

        jtxtKodePelanggan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtKodePelangganKeyPressed(evt);
            }
        });

        jLabel5.setText("Tanggal:");

        jfmtTanggalFaktur.setEditable(false);
        jfmtTanggalFaktur.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        jtxtGrandTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtGrandTotalKeyPressed(evt);
            }
        });

        jtblFaktur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Kode Barang", "Nama Barang", "Harga", "Qty", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblFaktur.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtblFakturPropertyChange(evt);
            }
        });
        jtblFaktur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtblFakturKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtblFaktur);
        jtblFaktur.getColumnModel().getColumn(0).setMinWidth(0);
        jtblFaktur.getColumnModel().getColumn(0).setPreferredWidth(0);
        jtblFaktur.getColumnModel().getColumn(0).setMaxWidth(0);

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jtxtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addGap(30, 30, 30)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jtxtKodePelanggan)
                                        .addComponent(jtxtNomorFaktur, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(30, 30, 30)
                                            .addComponent(jLabel5)
                                            .addGap(18, 18, 18)
                                            .addComponent(jfmtTanggalFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(40, 40, 40)
                                            .addComponent(jtxtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtNomorFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jfmtTanggalFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtKodePelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNomorFakturKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNomorFakturKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { 
            findData(); 
        }
    }//GEN-LAST:event_jtxtNomorFakturKeyPressed

    private void jtxtGrandTotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtGrandTotalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtGrandTotalKeyPressed

    private void jtxtKodePelangganKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtKodePelangganKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { 
            plg = plgctrl.findPelanggan(jtxtKodePelanggan.getText()); 
            if (plg == null) { 
                JOptionPane.showMessageDialog(null, jtxtKodePelanggan.getText() +  " Tidak Diketemukan "); 
                jtxtKodePelanggan.setText(""); 
                jtxtNamaPelanggan.setText(""); 
                jtxtKodePelanggan.requestFocus();  
                //cursor kembali ke kode 
            } else { 
                jtxtKodePelanggan.setText(plg.getKodepelanggan()); 
                jtxtNamaPelanggan.setText(plg.getNamapelanggan()); 
                jtblFaktur.requestFocus(); 
            } 
        }
    }//GEN-LAST:event_jtxtKodePelangganKeyPressed

    private void jtblFakturPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtblFakturPropertyChange
        // TODO add your handling code here:
        //ambil baris dan kolom yang terseleksi 
        int row = jtblFaktur.getSelectedRow(); 
        int col = jtblFaktur.getSelectedColumn(); 
         
        if ( row > -1) { 
            //jika ada yang terseleksi 
            if (col == 1) { 
                //jika kode barang (col 1) berubah 
                Barang brg = bctrl.findBarang(tmodelfaktur.getValueAt(row, col)+""); 
                if (brg != null ) { 
                    //jika kode barang (col 1) ketemu 
                    tmodelfaktur.setValueAt(brg.getKodebarang(), row, col); 
                    tmodelfaktur.setValueAt(brg.getNamabarang(), row, col + 1); 
                    tmodelfaktur.setValueAt(brg.getHargaStandard(), row, col + 2); 
                    jtblFaktur.changeSelection(row, col+3, false, false); 
                } else { 
                    //jika kode barang (col 1) tidak ketemu 
                    tmodelfaktur.setValueAt("", row, col + 1); 
                    tmodelfaktur.setValueAt(0, row, col + 2); 
                } 
            } 
            if (tmodelfaktur.getValueAt(tmodelfaktur.getRowCount()-1, 1)!= null){ 
                //jika nomor faktur tidak kosong  
                //dan baris terakhir tidak kosong maka tambah baris 
                tmodelfaktur.addRow(obj); 
            }             
            if (col == 4) { 
                jtblFaktur.changeSelection(tmodelfaktur.getRowCount()-1, 1, false, false); 
            } 
            hitungTotal();
        }
    }//GEN-LAST:event_jtblFakturPropertyChange

    private Boolean cariKodeBarang(int row) {
        String kodebarang = tmodelfaktur.getValueAt(row, 1)+"";
        if(!kodebarang.equals("")) {
            Barang brg = bctrl.findBarang(kodebarang);
            if (brg != null) {
                tmodelfaktur.setValueAt(brg.getNamabarang(), row, 2);
                tmodelfaktur.setValueAt(brg.getHargaStandard(), row, 3);                        
                return true;
            }
        }
        return false;
    }
    
    private void jtblFakturKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtblFakturKeyPressed
        // TODO add your handling code here:
        int row = jtblFaktur.getSelectedRow();
        int col = jtblFaktur.getSelectedColumn();
        if (evt.getKeyCode()==evt.VK_ENTER){
            evt.consume();
        }
        if (row > -1 ) {
            if (evt.getKeyCode() == KeyEvent.VK_F2) {
                if (col == 1 ) {
                    FrmBrowseBarang frmbrowse = new FrmBrowseBarang(jtblFaktur, row, col);
                    frmbrowse.setModal(true);
                    frmbrowse.setVisible(true);            
                    cariKodeBarang(row);
                    
                }
                    
            }
            

            
        }
    }//GEN-LAST:event_jtblFakturKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FrmBrowsePelanggan frmbrowse = new FrmBrowsePelanggan();
        frmbrowse.setFirstValue(jtxtKodePelanggan);
        frmbrowse.setSecondValue(jtxtNamaPelanggan);
        frmbrowse.setModal(true);
        frmbrowse.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JFormattedTextField jfmtTanggalFaktur;
    private javax.swing.JTable jtblFaktur;
    private javax.swing.JTextField jtxtGrandTotal;
    private javax.swing.JTextField jtxtKodePelanggan;
    private javax.swing.JTextField jtxtNamaPelanggan;
    private javax.swing.JTextField jtxtNomorFaktur;
    // End of variables declaration//GEN-END:variables

    @Override
    public void clearData() {
        //throw new UnsupportedOperationException("Not supported yet.");
        jfmtTanggalFaktur.setText(dfddmmyyyy.format(new Date())); 
        jtxtKodePelanggan.setText(""); 
        jtxtNamaPelanggan.setText(""); 
        clearTable();
    }

    @Override
    public void newData() {
        //throw new UnsupportedOperationException("Not supported yet.");
        jtxtNomorFaktur.setText(""); 
        clearData(); 
        tmodelfaktur.addRow(obj); 
        jtxtKodePelanggan.requestFocus();
    }

    @Override
    public void saveData() {
        //throw new UnsupportedOperationException("Not supported yet.");
        Faktur ffind = fctrl.findFaktur(jtxtNomorFaktur.getText()); 
        if (ffind == null) { 
            f = new Faktur(); 
            f.setNomorFaktur(fctrl.createNomorFaktur()); 
        } else { 
            f = ffind; 
        } 
        setData(); 
        Collection<Fakturdetail> colfkdt = new ArrayList<Fakturdetail>(); 
        for (int i = 0; i< tmodelfaktur.getRowCount(); i++) { 
            if (tmodelfaktur.getValueAt(i, 1) != null) { 
                Fakturdetail fdetail = new Fakturdetail(); 
                fdetail.setNomorFaktur(f); 
                if (tmodelfaktur.getValueAt(i, 0) != null) { 
                    fdetail.setId(Integer.parseInt(tmodelfaktur.getValueAt(i, 0)+"")); 
                } 
                setDataDetail(fdetail, i); 
                colfkdt.add(fdetail); 
            } 
        } 
        f.setFakturdetailCollection(colfkdt); 
        if (ffind == null) { 
            try { 
                fctrl.create(f); 
                jtxtNomorFaktur.setText(f.getNomorFaktur()); 
                JOptionPane.showMessageDialog(null, "Penyimpanan Faktur Berhasil"); 
            } catch (Exception ex) { 
                JOptionPane.showMessageDialog(null, "Penyimpanan Faktur Gagal : " + ex.getMessage()); 
            } 
        } else { 
            try { 
                fctrl.edit(f); 
                JOptionPane.showMessageDialog(null, "Penyimpanan Berhasil" ); 
            } catch (Exception ex) { 
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Penyimpanan Faktur Gagal : " + ex.getMessage()); 
            }              
        } 
        findData();
        printData();
    }

    @Override
    public void setData() {
        //throw new UnsupportedOperationException("Not supported yet.");
        plg = plgctrl.findPelanggan(jtxtKodePelanggan.getText()); 
        if (plg == null) { 
            jtxtKodePelanggan.setText(""); 
            jtxtNamaPelanggan.setText(""); 
        } 
        f.setKodePelanggan(plg); 
        try { 
            f.setTanggalFaktur(dfddmmyyyy.parse(jfmtTanggalFaktur.getText())); 
        } catch (ParseException ex) {}
    }

    @Override
    public void delete() {
        //throw new UnsupportedOperationException("Not supported yet.");
        try { 
            fctrl.destroy(jtxtNomorFaktur.getText()); 
            JOptionPane.showMessageDialog(null, "Penghapusan Selesai"); 
        } catch (Exception ex) { 
            JOptionPane.showMessageDialog(null,"Penghapusan tidak bisa karena " + ex.getMessage()); 
        } 
        clearData();
    }

    @Override
    public void findData() {
        //throw new UnsupportedOperationException("Not supported yet.");
        f = fctrl.findFaktur(jtxtNomorFaktur.getText()); 
        showData();
    }

    @Override
    public void showData() {
        //throw new UnsupportedOperationException("Not supported yet.");
        clearTable();
        if (f == null) { 
            newData(); 
        } else {
            jtxtNomorFaktur.setText(f.getNomorFaktur()); 
            jfmtTanggalFaktur.setText(dfddmmyyyy.format(f.getTanggalFaktur()));              
            if (f.getKodePelanggan() != null) { 
                jtxtKodePelanggan.setText(f.getKodePelanggan().getKodepelanggan()); 
                jtxtNamaPelanggan.setText(f.getKodePelanggan().getNamapelanggan()); 
            }         
            for (Fakturdetail fd : f.getFakturdetailCollection()) { 
                tmodelfaktur.addRow(obj); 
                tmodelfaktur.setValueAt(fd.getId(), tmodelfaktur.getRowCount() - 1, 0); 
                tmodelfaktur.setValueAt(fd.getKodeBarang().getKodebarang(), tmodelfaktur.getRowCount() - 1, 1); 
                tmodelfaktur.setValueAt(fd.getKodeBarang().getNamabarang(), tmodelfaktur.getRowCount() - 1, 2); 
                tmodelfaktur.setValueAt(fd.getHarga(), tmodelfaktur.getRowCount() - 1, 3); 
                tmodelfaktur.setValueAt(fd.getQty(), tmodelfaktur.getRowCount() - 1, 4); 
            } 
            hitungTotal(); 
            tmodelfaktur.addRow(obj);
        }
    }

    private void clearTable() { 
        int row = tmodelfaktur.getRowCount();       
        while(row > 0){   
            row--;         
            tmodelfaktur.removeRow(row); 
        }     
    }
    
    private void setDataDetail(Fakturdetail fdetail, int i){ 
        Barang b = bctrl.findBarang(tmodelfaktur.getValueAt(i, 1)+""); 
        fdetail.setKodeBarang(b); 
        double harga = 0; 
        try { 
            harga = Double.parseDouble(tmodelfaktur.getValueAt(i, 3)+""); 
        } catch (Exception e) {} 
        fdetail.setHarga(harga); 
        
        int qty = 0; 
        try { 
            qty = Integer.parseInt(tmodelfaktur.getValueAt(i, 4)+""); 
        } catch(Exception e) {} 
        fdetail.setQty(qty);                 
    }
    
    private void hitungTotal(){ 
        double grandtotal = 0; 
        try { 
            for (int i = 0; i < tmodelfaktur.getRowCount(); i++) { 
                double total  = 0; 
                total =  Double.parseDouble(tmodelfaktur.getValueAt(i, 3)+ "") *  
                Double.parseDouble(tmodelfaktur.getValueAt(i, 4)+""); 
                tmodelfaktur.setValueAt(total, i, 5); 
                grandtotal += total; 
            } 
        } catch(Exception e) {}  
        jtxtGrandTotal.setText(dftitik.format(grandtotal));
    }
    
    @Override
    public void printData() {
        //throw new UnsupportedOperationException("Not supported yet.");
        EntityManager em = null;     
        try { 
            em = AppPenjualan.emf.createEntityManager(); 
            em.getTransaction().begin();
            
            //code dibawah ini adalah milik Pak Windu, namun error di Netbeans saya
            //kemungkinan karena Lib Eclipselink (JPA) yang saya pakai
            //ternyata code di bawah ini compatible dengan java.sql.*
            //persistence menggunakan lib tersebut
            
            Connection connect = em.unwrap(Connection.class);
            
            //namun code diatas, dapat diakali dengan teknik di bawah ini
            //saya kurang tau juga, apakah code di bawah ini adalah menggunakan metode persistence atau tidak
            //tapi yang penting jalan toh... :D
            //salam imut dulu ahhh...
            //Connection connect = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/penjualan", "root", "P@ssw0rd");
            
            File file = new File("");  
            String sourcefilename = file.getAbsolutePath() + "\\src\\apppenjualan\\report\\Penjualan.jasper"; 
 
            HashMap hashmap = new HashMap(); 
            hashmap.put("nomorfaktur", jtxtNomorFaktur.getText()); 
  
            JasperPrint jprint = JasperFillManager.fillReport(sourcefilename, hashmap, connect); 
            JasperViewer viewer = new JasperViewer(jprint, false); 
            viewer.setFitPageZoomRatio(); 
            viewer.setVisible(true); 
 
            em.getTransaction().commit(); 
            connect.close(); 
        } catch (Exception e) { 
            e.printStackTrace(); 
            JOptionPane.showMessageDialog(null, "Tidak Bisa Print : " + e.getMessage());         
        } finally { 
            if (em != null) { 
                em.close(); 
            } 
        }
    }

    @Override
    public void moveFirst() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void movePrevious() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void moveNext() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void moveLast() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
